name: delete branch action

on:
  push:
    branches:
      # このアクションはmain または develop ブランチにプッシュされた際にのみ実行されます。
      - main
      - develop
      - es0215-patch-*
jobs:
  delete_hook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Delete branches
        run: |
          # ブランチ名がmainまたはdevelopでない場合、削除します。
          for branch in $(git for-each-ref --format '%(refname:short)' refs/heads/); do
            if [ "$branch" != "main" ] && [ "$branch" != "develop" ]; then
              git push origin --delete "$branch"
            fi
          done
